version: "3.8"
services:
    sp08-server:
        container_name: sp08-server
        build:
            context: .
            dockerfile: Dockerfile
        image: sp08server
        entrypoint: /bin/sh -c "composer install &&
            php artisan key:generate &&
            php artisan optimize &&
            php-fpm"
        volumes:
            - ./:/var/www/html
        networks:
            - ltct8-network
        depends_on:
            - sp08-db

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8088:443"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - ltct8-network
        depends_on:
            - sp08-server

    sp08-db:
        container_name: sp08-db
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ltct8-database:/var/lib/mysql
        env_file:
            - .env
        networks:
            - ltct8-network
networks:
    ltct8-network:
        driver: bridge

volumes:
    ltct8-database:
        driver: local
